/**
 * ReleansAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");

const controller = testerlib.MessageController;
const Response2001 = testerlib.Response2001;
const Response200 = testerlib.Response200;
const Response2002 = testerlib.Response2002;


describe("MessageController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * List all messages sent by the account.
     */
    it("should testGetAllMessages response", function testGetAllMessagesTest(done) {
        // parameters for the API call
        let accept = '*/*';

        controller.getAllMessages(accept, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        }).catch(() => undefined);
    });

    /**
     * Return the details of the message.
     */
    it("should testViewMessage response", function testViewMessageTest(done) {
        // parameters for the API call
        let id = 'id';
        let accept = '*/*';

        controller.getViewMessage(id, accept, function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        }).catch(() => undefined);
    });

});
