/**
 * ReleansAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Response2001 = require('../lib/Models/Response2001');
const Response200 = require('../lib/Models/Response200');
const Response2002 = require('../lib/Models/Response2002');

const classMap = {
    Response2001,
    Response200,
    Response2002,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
